description: "Paraguayan Crops Gardening Guide Test"

# ========== PROMPT CONFIGURATION ==========
# The 'prompts' section defines the prompt templates to be tested
# You can specify multiple prompts to compare different versions
prompts:
  - file://1-page-gardening-guide-prompt.txt

# ========== PROVIDER CONFIGURATION ==========
# 'providers' defines which LLM models/APIs will process your prompts
# Each provider has an 'id' that specifies the model and optional configuration
providers:
  # Active provider - this is the model that will actually run
  # - id: ollama:hf.co/MaziyarPanahi/ZYH-LLM-Qwen2.5-14B-V3-GGUF:Q5_K_M
  #   config:
  #     temperature: 0  # Controls randomness: 0 = deterministic, 1 = creative
      # Other possible parameters include:
      # max_tokens: 1000  # Maximum length of response
      # top_p: 0.9       # Nucleus sampling parameter
  
  # Commented out providers that can be uncommented for future testing
  # - id: ollama:gemma3:1b                ### BEST OVERALL PERFORMANCE
  #   config:
  #     temperature: 0

  # - id: openai:gpt-4o-mini
  #   config:
  #     temperature: 0
  #     # max_tokens: 128
  #     apiKey: sk-abc123

  - id: groq:llama-3.3-70b-versatile
    config:
      temperature: 0.7
      # max_completion_tokens: 100

# ========== TEST CASES ==========
# 'tests' define the different inputs to test with your prompts
# Each test case can have variables, descriptions, and assertions
tests:
  # Test case 1: Chayote squash
  # - vars:                                # Variables to substitute in the prompt
    #   BOTANICAL NAME: "Sechium edule"    # This replaces [BOTANICAL NAME] in the prompt
    # description: "Chayote squash gardening guide"  # Human-readable description
    # Placeholder for future assertions (commented out)
    # assert:                            # Assertions verify the output meets criteria
    #   - type: javascript               # Run JavaScript to validate output
    #     value: output.length <= 2500   # Approximate 350 word limit
    #   - type: contains                 # Check if output contains specific text
    #     value: "Local name (Spanish/Guaraní):"
  
  # Test case 2: Cassava
  - vars:
      BOTANICAL NAME: "Manihot esculenta"
    description: "Cassava gardening guide"
   
  
  # # Test case 3: Sweet potato
  # - vars:
  #     BOTANICAL NAME: "Ipomoea batatas"
  #   description: "Sweet potato gardening guide"
   
  
  # # Test case 4: Common bean
  # - vars:
  #     BOTANICAL NAME: "Phaseolus vulgaris"
  #   description: "Common bean gardening guide"
   

# ========== OUTPUT CONFIGURATION ==========
# Controls where and how results are saved
outputPath: "./results/gardening-guides-results.json"  # Path to save results
# The results will be saved in JSON format and can be viewed later


















# ========== ADVANCED CONFIGURATION ==========

# ========== EVALUATION OPTIONS ==========
# Controls how tests are executed (commented out for now)
# evaluateOptions:
#   maxConcurrency: 5       # Number of tests to run in parallel
#   showProgressBar: true   # Display progress during evaluation
#   cache: true             # Cache results to avoid re-running identical tests

# ========== TRANSFORMATIONS ==========
# Transformations process the output before evaluation or display
# These are JavaScript functions that can modify or extract data from outputs
# transforms:
#   - name: "Extract word count"
#     path: "./transforms/wordCount.js"  # Path to a JavaScript file
#   - name: "Check structure compliance"
#     path: "./transforms/structureCheck.js"
#   # You can also define inline transformations:
#   # - name: "Extract temperature"
#   #   function: |
#   #     (output) => {
#   #       const match = output.match(/(\d+)-(\d+)°C/);
#   #       return match ? { min: match[1], max: match[2] } : null;
#   #     }

# ========== SHARING OPTIONS ==========
# Controls how results can be shared with others (commented out for now)
# sharing:
#   enabled: true           # Enable sharing functionality
#   title: "Paraguayan Crops Gardening Guide Evaluation"
#   description: "Testing gardening guide generation for different crops in Paraguay"
#   # When enabled, promptfoo generates a shareable link to view results
